contact_links:
  - name: Richard's Telegram Channel
    url: https://t.me/richardtop
    about: News about CalendarKit and other projects
  - name: Video Tutorial
    url: https://youtu.be/cJ63-_z1qg8
    about: A complete tutorial of creating a Calendar app for iOS with CalendarKit
